### ISSUE TITLE
Add missing features related to combat

### ISSUE THREAD

**Issue by Kraken01** [BlowaXD/SaltyEmu#18]
There are still several features missing and that should be implemented to have a proper combat gameplay.

- [ ] Item drop on monster's death

- [ ] Damage calculation

- [ ] AOE Skills & Effects

- [ ] Monster aggressivity

- [ ] Buff

**Comment by BlowaXD** [comment]
Buffs are already implemented, however, it needs to be reviewed and the system needs to be changed like InventoryItemUsage (ItemUsage) and NpcDialogs.

BCard system should be moved to an async event one ;) (like here : https://github.com/BlowaXD/SaltyEmu/blob/master/src/Plugins/NosSharp.TemporaryMapPlugins/ItemUsageHandlers/UseItemHandlerAsync.cs)
