### ISSUE TITLE
Add a microservice to handle Relations & Gift

### ISSUE THREAD

**Issue by Kraken01** [BlowaXD/SaltyEmu#19]
The microservice should be written in GoLang and should handle these features :
- [ ] Relations 
- [ ] Friends
- [ ] Gifts

**Comment by BlowaXD** [comment]
Relations include : Friends / Blocked

Gifts is a separate microservice.

Technologies that I suggest : 
- gRPC
- GoLang
- Redis (for Gifts)
- MySQL / PostgreSQL for friends
