### ISSUE TITLE
Add hero chat

### ISSUE THREAD

**Issue by Zagith** [BlowaXD/SaltyEmu#20]
### **PacketName**

Hero
### Packet Usage

This packet is sent when a player in top 3 reputation write "+ message"
### Packet Header

hero
### Packet Content

**Sent by client:**
{Message}
### Few examples

hero {Message}

**Comment by BlowaXD** [comment]
Can you be a bit more descriptive about the hero chat ?

When is it used ? Who can use it ? Does it need some persistent storage ?
What is the expected behavior ?

Thanks
